export type ModuleDef={key:string;title:string;resource:string;desc:string;fields:{key:string;label:string;type?:string;required?:boolean}[]}
export const modules:ModuleDef[]=[
{key:'brands',title:'品牌管理',resource:'brands',desc:'品牌主数据及客户品牌关系',fields:[{key:'name',label:'品牌名称',required:true},{key:'website',label:'官网'},{key:'country',label:'国家'},{key:'group_name',label:'所属集团'},{key:'main_products',label:'主营产品'}]},
{key:'inquiries',title:'询盘管理',resource:'inquiries',desc:'客户询盘、需求、来源及状态',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'source',label:'来源'},{key:'status',label:'状态'},{key:'quantity',label:'数量'},{key:'target_price',label:'目标价'},{key:'incoterm',label:'贸易条款'},{key:'destination_port',label:'目的港'}]},
{key:'opportunities',title:'商机管理',resource:'opportunities',desc:'销售阶段、预计金额与竞争信息',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'name',label:'商机名称',required:true},{key:'stage',label:'阶段'},{key:'expected_amount',label:'预计金额',type:'number'},{key:'currency',label:'币种'},{key:'expected_close_date',label:'预计成交日',type:'date'},{key:'competitor',label:'竞争对手'}]},
{key:'quotations',title:'报价管理',resource:'quotations',desc:'报价版本、币种、贸易条款、付款、毛利',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'currency',label:'币种'},{key:'incoterm',label:'Incoterm'},{key:'payment_terms',label:'付款条件'},{key:'moq',label:'MOQ'},{key:'lead_time',label:'交期'},{key:'valid_until',label:'有效期',type:'date'},{key:'total',label:'总额',type:'number'}]},
{key:'samples',title:'样品管理',resource:'samples',desc:'样品申请、寄送、签收、反馈',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'product',label:'产品',required:true},{key:'quantity',label:'数量'},{key:'courier',label:'快递'},{key:'tracking_no',label:'运单号'},{key:'status',label:'状态'},{key:'feedback',label:'反馈'}]},
{key:'products',title:'产品与价格',resource:'products',desc:'产品、SKU、认证及基础价格',fields:[{key:'sku',label:'SKU'},{key:'name',label:'产品名称',required:true},{key:'category',label:'分类'},{key:'base_price',label:'基础价格',type:'number'},{key:'currency',label:'币种'}]},
{key:'contracts',title:'合同管理',resource:'contracts',desc:'合同、有效期、金额及附件',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'amount',label:'金额',type:'number'},{key:'currency',label:'币种'},{key:'signed_at',label:'签署日期',type:'date'},{key:'status',label:'状态'}]},
{key:'orders',title:'订单管理',resource:'orders',desc:'外贸订单、客户PO、交付状态',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'customer_po',label:'客户PO'},{key:'status',label:'状态'},{key:'currency',label:'币种'},{key:'incoterm',label:'贸易条款'},{key:'payment_terms',label:'付款条件'},{key:'total',label:'总额',type:'number'},{key:'requested_delivery',label:'要求交期',type:'date'}]},
{key:'payments',title:'回款管理',resource:'payments',desc:'应收、到账、逾期与银行流水',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'order_id',label:'订单ID'},{key:'amount',label:'金额',type:'number',required:true},{key:'currency',label:'币种'},{key:'due_at',label:'应付日期',type:'date'},{key:'paid_at',label:'到账日期',type:'date'},{key:'status',label:'状态'}]},
{key:'shipments',title:'出运与物流',resource:'shipments',desc:'订舱、柜型、船期、BL、港口及物流跟踪',fields:[{key:'order_id',label:'订单ID',required:true},{key:'booking_no',label:'订舱号'},{key:'carrier',label:'船公司'},{key:'forwarder',label:'货代'},{key:'container_type',label:'柜型'},{key:'container_no',label:'柜号'},{key:'bl_no',label:'提单号'},{key:'etd',label:'ETD',type:'date'},{key:'eta',label:'ETA',type:'date'},{key:'status',label:'状态'}]},
{key:'aftersales',title:'售后与投诉',resource:'aftersales',desc:'客诉工单、严重度、责任部门与解决方案',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'category',label:'问题分类',required:true},{key:'severity',label:'严重度'},{key:'subject',label:'主题',required:true},{key:'description',label:'问题描述',required:true},{key:'responsible_team',label:'责任部门'},{key:'solution',label:'解决方案'},{key:'status',label:'状态'}]},
{key:'campaigns',title:'客户营销',resource:'campaigns',desc:'客户分群、营销活动及触达内容',fields:[{key:'name',label:'活动名称',required:true},{key:'type',label:'类型',required:true},{key:'status',label:'状态'},{key:'scheduled_at',label:'计划时间',type:'datetime-local'},{key:'content',label:'内容'}]},
{key:'customFields',title:'自定义字段',resource:'customFields',desc:'客户属性等动态字段配置',fields:[{key:'entity_type',label:'实体',required:true},{key:'field_key',label:'字段Key',required:true},{key:'label',label:'显示名称',required:true},{key:'data_type',label:'数据类型',required:true},{key:'group_name',label:'字段分组'},{key:'sort_order',label:'排序',type:'number'}]},
{key:'tasks',title:'任务与提醒',resource:'tasks',desc:'跟进任务、到期提醒与责任人',fields:[{key:'customer_id',label:'客户ID'},{key:'title',label:'任务',required:true},{key:'description',label:'说明'},{key:'due_at',label:'截止时间',type:'datetime-local'},{key:'priority',label:'优先级'},{key:'status',label:'状态'}]},
{key:'activities',title:'跟进记录',resource:'activities',desc:'电话、邮件、WhatsApp、拜访、会议等沟通历史',fields:[{key:'customer_id',label:'客户ID',required:true},{key:'contact_id',label:'联系人ID'},{key:'type',label:'跟进方式',required:true},{key:'subject',label:'主题'},{key:'content',label:'沟通内容',required:true},{key:'result',label:'结果'},{key:'next_action',label:'下一步'},{key:'occurred_at',label:'发生时间',type:'datetime-local'}]},
{key:'documents',title:'文档与附件',resource:'documents',desc:'合同、报价、授权书、CI/PL/BL等文档元数据',fields:[{key:'entity_type',label:'关联类型',required:true},{key:'entity_id',label:'关联ID',required:true},{key:'category',label:'分类'},{key:'name',label:'文件名',required:true},{key:'version',label:'版本'},{key:'url',label:'URL'}]},
{key:'users',title:'用户与权限',resource:'users',desc:'系统用户与角色（仅管理员）',fields:[{key:'username',label:'用户名',required:true},{key:'display_name',label:'姓名',required:true},{key:'role',label:'角色',required:true},{key:'password',label:'初始/新密码',type:'password'}]}
]
