<script setup lang="ts">
import {ref,reactive,onMounted,computed} from 'vue';import {ElMessage} from 'element-plus';import AppLayout from '../layouts/AppLayout.vue';import {api} from '../api/client';
const rows=ref<any[]>([]),customers=ref<any[]>([]),contacts=ref<any[]>([]),dialog=ref(false),convertDialog=ref(false),selected=ref<any>(null);
const form=reactive<any>({customer_id:'',contact_id:'',source:'Website',status:'new',products:[],quantity:'',target_price:'',incoterm:'FOB',destination_port:'',requested_delivery:'',received_at:new Date().toISOString().slice(0,16),notes:''});
const conv=reactive<any>({name:'',expected_amount:0,currency:'USD',expected_close_date:'',probability:20,competitor:'',notes:''});
const customerMap=computed(()=>Object.fromEntries(customers.value.map(x=>[x.id,x.name])));
const filteredContacts=computed(()=>contacts.value.filter(x=>x.customer_id===form.customer_id));
async function load(){rows.value=(await api.get('/inquiries',{params:{size:200}})).data.data;customers.value=(await api.get('/customers',{params:{size:200}})).data.data;contacts.value=(await api.get('/contacts',{params:{size:500}})).data.data}
async function save(){if(!form.customer_id)return ElMessage.warning('请选择客户');await api.post('/inquiries',{...form,received_at:new Date(form.received_at).toISOString()});dialog.value=false;await load();ElMessage.success('询盘已创建')}
function openConvert(r:any){selected.value=r;Object.assign(conv,{name:`${customerMap.value[r.customer_id]||''} - ${r.inquiry_no}`,expected_amount:0,currency:'USD',expected_close_date:'',probability:20,competitor:'',notes:r.notes||''});convertDialog.value=true}
async function convert(){await api.post(`/workflows/inquiries/${selected.value.id}/to-opportunity`,conv);convertDialog.value=false;await load();ElMessage.success('已转为商机')}
onMounted(load);
</script>
<template><AppLayout><div class="toolbar"><div><h2 style="margin:0">询盘管理</h2><span class="muted">从客户需求进入销售漏斗</span></div><el-button type="primary" @click="dialog=true">新增询盘</el-button></div>
<div class="card"><el-table :data="rows"><el-table-column prop="inquiry_no" label="询盘编号" width="180"/><el-table-column label="客户" min-width="180"><template #default="s">{{customerMap[s.row.customer_id]||s.row.customer_id}}</template></el-table-column><el-table-column label="产品" min-width="180"><template #default="s">{{(s.row.products||[]).join('、')||'-'}}</template></el-table-column><el-table-column prop="quantity" label="数量"/><el-table-column prop="target_price" label="目标价"/><el-table-column prop="incoterm" label="贸易条款"/><el-table-column prop="destination_port" label="目的港"/><el-table-column prop="status" label="状态" width="110"><template #default="s"><el-tag :type="s.row.status==='converted'?'success':'info'">{{s.row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="120"><template #default="s"><el-button v-if="s.row.status!=='converted'" link type="primary" @click="openConvert(s.row)">转商机</el-button></template></el-table-column></el-table></div>
<el-dialog v-model="dialog" title="新增询盘" width="760"><el-form label-position="top"><div class="grid" style="grid-template-columns:1fr 1fr">
<el-form-item label="客户"><el-select v-model="form.customer_id" filterable style="width:100%" @change="form.contact_id=''"><el-option v-for="c in customers" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="联系人"><el-select v-model="form.contact_id" clearable style="width:100%"><el-option v-for="c in filteredContacts" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item>
<el-form-item label="来源"><el-input v-model="form.source"/></el-form-item><el-form-item label="收到时间"><el-input v-model="form.received_at" type="datetime-local"/></el-form-item>
<el-form-item label="产品"><el-select v-model="form.products" multiple allow-create filterable style="width:100%" placeholder="输入产品后回车"/></el-form-item><el-form-item label="数量"><el-input v-model="form.quantity"/></el-form-item>
<el-form-item label="目标价"><el-input v-model="form.target_price"/></el-form-item><el-form-item label="Incoterm"><el-select v-model="form.incoterm" style="width:100%"><el-option v-for="x in ['EXW','FOB','CFR','CIF','DAP','DDP']" :key="x" :label="x" :value="x"/></el-select></el-form-item>
<el-form-item label="目的港"><el-input v-model="form.destination_port"/></el-form-item><el-form-item label="期望交期"><el-input v-model="form.requested_delivery" type="date"/></el-form-item></div><el-form-item label="备注"><el-input v-model="form.notes" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存询盘</el-button></template></el-dialog>
<el-dialog v-model="convertDialog" title="询盘转商机" width="620"><el-form label-position="top"><el-form-item label="商机名称"><el-input v-model="conv.name"/></el-form-item><div class="grid" style="grid-template-columns:1fr 1fr"><el-form-item label="预计金额"><el-input v-model.number="conv.expected_amount" type="number"/></el-form-item><el-form-item label="币种"><el-select v-model="conv.currency" style="width:100%"><el-option v-for="x in ['USD','EUR','GBP','CNY']" :key="x" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="预计成交日"><el-input v-model="conv.expected_close_date" type="date"/></el-form-item><el-form-item label="成交概率 %"><el-input v-model.number="conv.probability" type="number"/></el-form-item></div><el-form-item label="竞争对手"><el-input v-model="conv.competitor"/></el-form-item><el-form-item label="备注"><el-input v-model="conv.notes" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="convertDialog=false">取消</el-button><el-button type="primary" @click="convert">确认转商机</el-button></template></el-dialog>
</AppLayout></template>