<script setup lang="ts">
import {ref,reactive,onMounted,computed} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import AppLayout from '../layouts/AppLayout.vue';import {api} from '../api/client';import {useAuth} from '../stores/auth';
const auth=useAuth();if(!auth.user)auth.me().catch(()=>{});const canSeeCost=computed(()=>['admin','manager'].includes(auth.user?.role));const canManageApproval=computed(()=>['admin','manager'].includes(auth.user?.role));
const rows=ref<any[]>([]),customers=ref<any[]>([]),detail=ref<any>(null),evaluation=ref<any>(null),drawer=ref(false),itemDialog=ref(false),orderDialog=ref(false),policyDialog=ref(false),rejectDialog=ref(false);
const item=reactive<any>({product_code:'',product_name:'',quantity:1,unit:'pcs',unit_price:0,cost:0,spec:''});
const order=reactive<any>({customer_po:'',requested_delivery:'',notes:''});
const policy=reactive<any>({min_margin_rate:20,max_discount_percent:10,special_payment_keywords:['OA','D/P','D/A'],block_below_floor_price:true});
const rejectForm=reactive<any>({comment:''});
const customerMap=computed(()=>Object.fromEntries(customers.value.map(x=>[x.id,x.name])));
async function load(){rows.value=(await api.get('/quotations',{params:{size:200}})).data.data;customers.value=(await api.get('/customers',{params:{size:200}})).data.data}
async function loadEvaluation(){if(detail.value)evaluation.value=(await api.get(`/workflows/quotations/${detail.value.id}/evaluation`)).data}
async function open(r:any){detail.value=(await api.get(`/workflows/quotations/${r.id}/full`)).data;await loadEvaluation();drawer.value=true}
async function refresh(){if(detail.value){detail.value=(await api.get(`/workflows/quotations/${detail.value.id}/full`)).data;await loadEvaluation()}await load()}
async function addItem(){if(!item.product_name)return ElMessage.warning('请输入产品名称');await api.post('/quotationItems',{...item,quotation_id:detail.value.id,amount:Number(item.quantity)*Number(item.unit_price)});itemDialog.value=false;Object.assign(item,{product_code:'',product_name:'',quantity:1,unit:'pcs',unit_price:0,cost:0,spec:''});await api.post(`/workflows/quotations/${detail.value.id}/recalculate`,{});await refresh()}
async function delItem(r:any){await ElMessageBox.confirm('确认删除此报价明细？','确认');await api.delete(`/quotationItems/${r.id}`);await api.post(`/workflows/quotations/${detail.value.id}/recalculate`,{});await refresh()}
async function recalc(){detail.value=(await api.post(`/workflows/quotations/${detail.value.id}/recalculate`,{})).data;await load();ElMessage.success('报价金额已重算')}
async function copyVersion(){const {data}=await api.post(`/workflows/quotations/${detail.value.id}/copy-version`,{});ElMessage.success(`已生成 V${data.version}：${data.quote_no}`);await load();await open(data)}
async function submit(){
  try{
    const {data}=await api.post(`/workflows/quotations/${detail.value.id}/submit`,{});
    await refresh();
    ElMessage.success(data.auto_approved?'未触发风险规则，报价已自动通过':'已提交条件审批');
  }catch(e:any){
    if(e.response?.data?.error==='below_floor_price'){evaluation.value=e.response.data.evaluation;ElMessage.error('存在低于产品底价的报价明细，已阻止提交');return}
    throw e
  }
}
async function approve(){try{await api.post(`/workflows/quotations/${detail.value.id}/approve`,{});await refresh();ElMessage.success('报价已批准')}catch(e:any){ElMessage.error(e.response?.status===403?'仅管理员/经理可批准':'审批失败')}}
async function reject(){await api.post(`/workflows/quotations/${detail.value.id}/reject`,rejectForm);rejectDialog.value=false;rejectForm.comment='';await refresh();ElMessage.success('报价已驳回')}
async function openPolicy(){Object.assign(policy,(await api.get('/quotations/approval-policy')).data);policyDialog.value=true}
async function savePolicy(){await api.put('/quotations/approval-policy',policy);policyDialog.value=false;await loadEvaluation();ElMessage.success('审批策略已保存')}
async function toOrder(){const {data}=await api.post(`/workflows/quotations/${detail.value.id}/to-order`,order);orderDialog.value=false;await refresh();ElMessage.success(`已生成订单 ${data.order_no}`)}
async function updateHeader(){const p={incoterm:detail.value.incoterm,payment_terms:detail.value.payment_terms,moq:detail.value.moq,packaging:detail.value.packaging,lead_time:detail.value.lead_time,valid_until:detail.value.valid_until,discount:Number(detail.value.discount||0),notes:detail.value.notes};await api.patch(`/quotations/${detail.value.id}`,p);await recalc();await loadEvaluation()}
onMounted(load);
</script>
<template><AppLayout><div class="toolbar"><div><h2 style="margin:0">报价管理</h2><span class="muted">版本、产品明细、底价红线、条件审批与订单转换</span></div><el-button v-if="canManageApproval" @click="openPolicy">审批策略</el-button></div>
<div class="card"><el-table :data="rows" @row-dblclick="open"><el-table-column prop="quote_no" label="报价编号" width="180"/><el-table-column prop="version" label="版本" width="70"><template #default="s">V{{s.row.version}}</template></el-table-column><el-table-column label="客户" min-width="180"><template #default="s">{{customerMap[s.row.customer_id]||s.row.customer_id}}</template></el-table-column><el-table-column prop="incoterm" label="条款"/><el-table-column label="总额" width="150"><template #default="s">{{s.row.currency}} {{Number(s.row.total||0).toLocaleString()}}</template></el-table-column><el-table-column v-if="canSeeCost" label="毛利率" width="100"><template #default="s">{{s.row.margin_rate==null?'-':Number(s.row.margin_rate).toFixed(1)+'%'}}</template></el-table-column><el-table-column prop="valid_until" label="有效期"/><el-table-column prop="status" label="状态" width="130"/><el-table-column label="操作" width="90"><template #default="s"><el-button link type="primary" @click="open(s.row)">详情</el-button></template></el-table-column></el-table></div>
<el-drawer v-model="drawer" size="78%" title="报价详情"><template v-if="detail"><div class="toolbar"><div><h3 style="margin:0">{{detail.quote_no}} · V{{detail.version}}</h3><span class="muted">{{customerMap[detail.customer_id]}} · {{detail.status}}</span></div><div><el-button @click="copyVersion">复制新版本</el-button><el-button @click="submit" :disabled="!['draft','rejected'].includes(detail.status)">提交报价</el-button><el-button v-if="canManageApproval" type="success" @click="approve" :disabled="detail.status!=='pending_approval'">批准</el-button><el-button v-if="canManageApproval" type="danger" plain @click="rejectDialog=true" :disabled="detail.status!=='pending_approval'">驳回</el-button><el-button type="primary" @click="orderDialog=true" :disabled="!['approved','sent','accepted'].includes(detail.status)">转订单</el-button></div></div>
<div v-if="evaluation" class="card" style="margin-bottom:16px">
  <div class="toolbar"><div><h3 class="section-title">报价风险评估</h3><span class="muted">提交时由系统规则自动判断</span></div><el-tag :type="evaluation.blocked?'danger':evaluation.requires_approval?'warning':'success'">{{evaluation.blocked?'禁止提交':evaluation.requires_approval?'需要审批':'可自动通过'}}</el-tag></div>
  <el-alert v-if="evaluation.blocked" type="error" :closable="false" title="存在低于产品底价的明细，必须先调整报价。"/>
  <div v-if="evaluation.reasons?.length" style="margin-top:10px"><el-tag v-for="r in evaluation.reasons" :key="r.code" :type="r.code==='below_floor_price'?'danger':'warning'" style="margin:0 6px 6px 0">{{r.label}}</el-tag></div>
  <el-table v-if="evaluation.below_floor_items?.length" :data="evaluation.below_floor_items" size="small" style="margin-top:8px"><el-table-column prop="product_name" label="低于底价产品"/><el-table-column prop="unit_price" label="报价单价"/><el-table-column prop="floor_price" label="底价"/></el-table>
</div>
<div class="card" style="margin-bottom:16px"><div class="grid" style="grid-template-columns:repeat(4,1fr)"><el-form-item label="Incoterm"><el-input v-model="detail.incoterm"/></el-form-item><el-form-item label="付款条件"><el-input v-model="detail.payment_terms"/></el-form-item><el-form-item label="MOQ"><el-input v-model="detail.moq"/></el-form-item><el-form-item label="包装"><el-input v-model="detail.packaging"/></el-form-item><el-form-item label="交期"><el-input v-model="detail.lead_time"/></el-form-item><el-form-item label="有效期"><el-input v-model="detail.valid_until" type="date"/></el-form-item><el-form-item label="折扣金额"><el-input v-model.number="detail.discount" type="number"/></el-form-item><el-form-item label="备注"><el-input v-model="detail.notes"/></el-form-item></div><el-button @click="updateHeader">保存报价头信息</el-button></div>
<div class="card"><div class="toolbar"><h3 class="section-title">产品明细</h3><div><el-button @click="recalc">重算金额</el-button><el-button type="primary" @click="itemDialog=true">添加产品</el-button></div></div><el-table :data="detail.items"><el-table-column prop="product_code" label="编码"/><el-table-column prop="product_name" label="产品" min-width="180"/><el-table-column prop="spec" label="规格"/><el-table-column prop="quantity" label="数量"/><el-table-column prop="unit" label="单位"/><el-table-column prop="unit_price" label="单价"/><el-table-column v-if="canSeeCost" prop="cost" label="成本"/><el-table-column prop="amount" label="小计"/><el-table-column label="操作" width="80"><template #default="s"><el-button link type="danger" @click="delItem(s.row)">删除</el-button></template></el-table-column></el-table>
<div style="display:flex;justify-content:flex-end;margin-top:16px"><el-descriptions :column="1" border style="width:360px"><el-descriptions-item label="小计">{{detail.currency}} {{Number(detail.subtotal||0).toFixed(2)}}</el-descriptions-item><el-descriptions-item label="折扣">- {{detail.currency}} {{Number(detail.discount||0).toFixed(2)}}</el-descriptions-item><el-descriptions-item label="总额"><b>{{detail.currency}} {{Number(detail.total||0).toFixed(2)}}</b></el-descriptions-item><el-descriptions-item v-if="canSeeCost" label="毛利率">{{detail.margin_rate==null?'-':Number(detail.margin_rate).toFixed(2)+'%'}}</el-descriptions-item></el-descriptions></div></div></template></el-drawer>
<el-dialog v-model="itemDialog" title="添加报价产品" width="680"><el-form label-position="top"><div class="grid" style="grid-template-columns:1fr 1fr"><el-form-item label="产品编码"><el-input v-model="item.product_code"/></el-form-item><el-form-item label="产品名称"><el-input v-model="item.product_name"/></el-form-item><el-form-item label="规格"><el-input v-model="item.spec"/></el-form-item><el-form-item label="数量"><el-input v-model.number="item.quantity" type="number"/></el-form-item><el-form-item label="单位"><el-input v-model="item.unit"/></el-form-item><el-form-item label="单价"><el-input v-model.number="item.unit_price" type="number"/></el-form-item><el-form-item v-if="canSeeCost" label="成本"><el-input v-model.number="item.cost" type="number"/></el-form-item></div></el-form><template #footer><el-button @click="itemDialog=false">取消</el-button><el-button type="primary" @click="addItem">添加并重算</el-button></template></el-dialog>
<el-dialog v-model="orderDialog" title="报价转订单" width="560"><el-form label-position="top"><el-form-item label="客户PO"><el-input v-model="order.customer_po"/></el-form-item><el-form-item label="要求交期"><el-input v-model="order.requested_delivery" type="date"/></el-form-item><el-form-item label="备注"><el-input v-model="order.notes" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="orderDialog=false">取消</el-button><el-button type="primary" @click="toOrder">生成订单</el-button></template></el-dialog>
<el-dialog v-model="policyDialog" title="报价审批策略" width="620"><el-form label-position="top"><div class="grid" style="grid-template-columns:1fr 1fr"><el-form-item label="最低毛利率 %"><el-input-number v-model="policy.min_margin_rate" :min="0" :max="100"/></el-form-item><el-form-item label="最大免审批折扣 %"><el-input-number v-model="policy.max_discount_percent" :min="0" :max="100"/></el-form-item></div><el-form-item label="特殊付款条件关键词"><el-select v-model="policy.special_payment_keywords" multiple allow-create filterable style="width:100%"/></el-form-item><el-form-item><el-checkbox v-model="policy.block_below_floor_price">低于产品底价时直接阻止提交</el-checkbox></el-form-item></el-form><template #footer><el-button @click="policyDialog=false">取消</el-button><el-button type="primary" @click="savePolicy">保存策略</el-button></template></el-dialog>
<el-dialog v-model="rejectDialog" title="驳回报价" width="520"><el-form label-position="top"><el-form-item label="驳回说明"><el-input v-model="rejectForm.comment" type="textarea" :rows="4" placeholder="说明需要调整的价格、毛利、付款条件等"/></el-form-item></el-form><template #footer><el-button @click="rejectDialog=false">取消</el-button><el-button type="danger" @click="reject">确认驳回</el-button></template></el-dialog>
</AppLayout></template>